In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from scipy.stats import shapiro
import scipy.stats
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import bartlett
from statsmodels.api import Logit

In [ ]:
df = pd.read_csv("최종데이터.csv",encoding = 'euc - kr')
df

생산일자      품목코드 작업장코드      충전실온도        실링온도        쿠킹온도  쿠킹스팀압력  \
0     2021-01-06  13K03115  W007  71.532674  102.332674  138.021424  23.793   
1     2021-01-06  13K03115  W007  71.532674  102.332674  138.021424  23.793   
2     2021-01-06  13K03115  W007  71.532674  102.332674  138.021424  23.793   
3     2021-01-06  13K03115  W007  71.532674  102.332674  138.021424  23.793   
4     2021-01-06  13K03115  W007  71.532674  102.332674  138.021424  23.793   
...          ...       ...   ...        ...         ...         ...     ...   
9935  2021-10-28  1BA03593  W005  73.504287   94.304287  129.620537  23.544   
9936  2021-10-27  13D02345  W007  72.768358  118.968358  154.903658  23.957   
9937  2021-10-28  13D02286  W005  72.218250  112.318250  147.606400  23.525   
9938  2021-10-28  13D02286  W005  72.218250  112.318250  147.606400  23.525   
9939  2021-10-29  16B06118  W007  71.015225  106.115225  141.148725  23.356   

       생산시간 불량여부 발생시간 종료시간  오류발생Hour  오류조치시간 비가동코드 Error_Message 오류발생작업장명  \
0     77.10   양품    0    0         0     0.0     0             0        0   
1     77.10   양품    0    0         0     0.0     0             0        0   
2     77.10   양품    0    0         0     0.0     0             0        0   
3     77.10   양품    0    0         0     0.0     0             0        0   
4     77.10   양품    0    0         0     0.0     0             0        0   
...     ...  ...  ...  ...       ...     ...   ...           ...      ...   
9935  73.10   양품    0    0         0     0.0     0             0        0   
9936  74.30   양품    0    0         0     0.0     0             0        0   
9937  71.56   양품    0    0         0     0.0     0             0        0   
9938  71.56   양품    0    0         0     0.0     0             0        0   
9939  76.03   양품    0    0         0     0.0     0             0        0   

        수주단가         수주금액 출하완료여부        납기일자  
0     4025.0     16100.00      Y  20210106.0  
1     4025.0      4025.00      Y  20210106.0  
2     4025.0     36225.00      Y  20210106.0  
3     4000.0    363637.00      Y  20210107.0  
4     3850.0    192500.00      Y  20210107.0  
...      ...          ...    ...         ...  
9935  8710.0  34240752.00      Y  20211029.0  
9936  2010.0    785015.55      Y  20211027.0  
9937  1096.0    445578.80      Y  20211028.0  
9938  1071.0      1006.74      Y  20211029.0  
9939  5775.0     11550.00      Y  20211029.0  

[9940 rows x 20 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9940 entries, 0 to 9939
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   생산일자           9940 non-null   object 
 1   품목코드           9940 non-null   object 
 2   작업장코드          9940 non-null   object 
 3   충전실온도          9940 non-null   float64
 4   실링온도           9940 non-null   float64
 5   쿠킹온도           9940 non-null   float64
 6   쿠킹스팀압력         9940 non-null   float64
 7   생산시간           9940 non-null   float64
 8   불량여부           9940 non-null   object 
 9   발생시간           9940 non-null   object 
 10  종료시간           9940 non-null   object 
 11  오류발생Hour       9940 non-null   int64  
 12  오류조치시간         9940 non-null   float64
 13  비가동코드          9940 non-null   object 
 14  Error_Message  9940 non-null   object 
 15  오류발생작업장명       9940 non-null   object 
 16  수주단가           9940 non-null   float64
 17  수주금액           9940 non-null   float64
 18  출하완료여부  

In [ ]:
생산일자_pivot_df= df.pivot_table(index='생산일자', columns='출하완료여부', fill_value=0, aggfunc='size')
생산일자_pivot_df

출하완료여부      N   Y
생산일자             
2016-01-13  0   1
2016-01-20  0   1
2016-01-22  0   2
2016-01-28  0  10
2016-02-10  0   2
...        ..  ..
2021-10-27  3   6
2021-10-28  0   3
2021-10-29  0   1
2021-11-01  3   4
2021-11-02  3   0

[1085 rows x 2 columns]

In [ ]:
chi,pval,dof,expected = stats.chi2_contingency(생산일자_pivot_df)

print("chi-square test")
print("chisq : %.3f"%chi)
print("p : %f"%pval)
print("dgree of freedom : %.3f"%dof)
print("expected value : \n{}".format(expected.round(3))) # p-value < 0.5 대립가설 채택

chi-square test
chisq : 3924.339
p : 0.000000
dgree of freedom : 1084.000
expected value : 
[[4.000e-03 9.960e-01]
 [4.000e-03 9.960e-01]
 [8.000e-03 1.992e+00]
 ...
 [4.000e-03 9.960e-01]
 [2.700e-02 6.973e+00]
 [1.100e-02 2.989e+00]]


In [ ]:
작업장코드_pivot_df= df.pivot_table(index='작업장코드', columns='출하완료여부', fill_value=0, aggfunc='size')
작업장코드_pivot_df

출하완료여부   N     Y
작업장코드           
W005    37  7630
W007     1  2272

In [ ]:
chi,pval,dof,expected = stats.chi2_contingency(작업장코드_pivot_df)

print("chi-square test")
print("chisq : %.3f"%chi)
print("p : %f"%pval)
print("dgree of freedom : %.3f"%dof)
print("expected value : \n{}".format(expected.round(3))) # p-value < 0.5 대립가설 채택

chi-square test
chisq : 7.742
p : 0.005396
dgree of freedom : 1.000
expected value : 
[[  29.31 7637.69]
 [   8.69 2264.31]]


In [ ]:
불량여부_pivot_df= df.pivot_table(index='불량여부', columns='출하완료여부', fill_value=0, aggfunc='size')
불량여부_pivot_df

출하완료여부   N     Y
불량여부            
불량       0   423
양품      38  9479

In [ ]:
chi,pval,dof,expected = stats.chi2_contingency(불량여부_pivot_df)

print("chi-square test")
print("chisq : %.3f"%chi)
print("p : %f"%pval)
print("dgree of freedom : %.3f"%dof)
print("expected value : \n{}".format(expected.round(3))) # p-value > 0.5 귀무가설 채택

chi-square test
chisq : 0.809
p : 0.368389
dgree of freedom : 1.000
expected value : 
[[1.617000e+00 4.213830e+02]
 [3.638300e+01 9.480617e+03]]
